/* tslint:disable */
/* eslint-disable */
/**
 * OPENCOURIER-API
 * OpenCourier Backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';

/**
 * 
 * @export
 * @interface DeliveryReassignAdminInput
 */
export interface DeliveryReassignAdminInput {
    /**
     * 
     * @type {string}
     * @memberof DeliveryReassignAdminInput
     */
    courierId: string;
    /**
     * A key from the votable Config menu (`reassignmentPayoutPolicies`). Omit to let the backend apply the configured default. Never a free-text amount.
     * @type {string}
     * @memberof DeliveryReassignAdminInput
     */
    payoutPolicy?: string;
    /**
     * 
     * @type {string}
     * @memberof DeliveryReassignAdminInput
     */
    message?: string;
}

/**
 * Check if a given object implements the DeliveryReassignAdminInput interface.
 */
export function instanceOfDeliveryReassignAdminInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "courierId" in value;

    return isInstance;
}

export function DeliveryReassignAdminInputFromJSON(json: any): DeliveryReassignAdminInput {
    return DeliveryReassignAdminInputFromJSONTyped(json, false);
}

export function DeliveryReassignAdminInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeliveryReassignAdminInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'courierId': json['courierId'],
        'payoutPolicy': !exists(json, 'payoutPolicy') ? undefined : json['payoutPolicy'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function DeliveryReassignAdminInputToJSON(value?: DeliveryReassignAdminInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'courierId': value.courierId,
        'payoutPolicy': value.payoutPolicy,
        'message': value.message,
    };
}
