/* tslint:disable */
/* eslint-disable */
/**
 * OPENCOURIER-API
 * OpenCourier Backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';

/**
 * 
 * @export
 * @interface DeliveryEventAdminDto
 */
export interface DeliveryEventAdminDto {
    id: string;
    // Plain `string`, not adminweb's EnumDeliveryEventType: the backend also emits
    // REASSIGNED, which that enum does not list. A narrower type would make a real value
    // impossible to represent.
    type: string;
    actor: string;          // 'ADMIN' | 'COURIER' | 'PARTNER'
    eventSource: string;    // 'OPENCOURIER' | 'PARTNER_APP' — the API field is eventSource, NOT source
    oldStatus: string | null;
    newStatus: string | null;
    // false = the transition was attempted and recorded but did not take effect.
    transitionSuccessful: boolean;
    message: string | null;
    createdAt: Date;
}

/**
 * Check if a given object implements the DeliveryEventAdminDto interface.
 */
export function instanceOfDeliveryEventAdminDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "transitionSuccessful" in value;

    return isInstance;
}

export function DeliveryEventAdminDtoFromJSON(json: any): DeliveryEventAdminDto {
    return DeliveryEventAdminDtoFromJSONTyped(json, false);
}

export function DeliveryEventAdminDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeliveryEventAdminDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'id': json['id'],
        'type': json['type'],
        'actor': json['actor'],
        'eventSource': json['eventSource'],
        'oldStatus': json['oldStatus'] === undefined ? null : json['oldStatus'],
        'newStatus': json['newStatus'] === undefined ? null : json['newStatus'],
        'transitionSuccessful': json['transitionSuccessful'],
        'message': json['message'] === undefined ? null : json['message'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function DeliveryEventAdminDtoToJSON(value?: DeliveryEventAdminDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'id': value.id,
        'type': value.type,
        'actor': value.actor,
        'eventSource': value.eventSource,
        'oldStatus': value.oldStatus,
        'newStatus': value.newStatus,
        'transitionSuccessful': value.transitionSuccessful,
        'message': value.message,
        'createdAt': (value.createdAt.toISOString()),
    };
}
