/* tslint:disable */
/* eslint-disable */
/**
 * OPENCOURIER-API
 * OpenCourier Backend API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface InstanceConfigSettingsAdminInput
 */
export interface InstanceConfigSettingsAdminInput {
  /**
   *
   * @type {string}
   * @memberof InstanceConfigSettingsAdminInput
   */
  courierMatcherType?: InstanceConfigSettingsAdminInputCourierMatcherTypeEnum;
  /**
   *
   * @type {string}
   * @memberof InstanceConfigSettingsAdminInput
   */
  quoteCalculationType?: InstanceConfigSettingsAdminInputQuoteCalculationTypeEnum;
  /**
   *
   * @type {string}
   * @memberof InstanceConfigSettingsAdminInput
   */
  geoCalculationType?: InstanceConfigSettingsAdminInputGeoCalculationTypeEnum;
  /**
   *
   * @type {string}
   * @memberof InstanceConfigSettingsAdminInput
   */
  deliveryDurationCalculationType?: InstanceConfigSettingsAdminInputDeliveryDurationCalculationTypeEnum;
  /**
   *
   * @type {string}
   * @memberof InstanceConfigSettingsAdminInput
   */
  courierCompensationCalculationType?: InstanceConfigSettingsAdminInputCourierCompensationCalculationTypeEnum;
  /**
   *
   * @type {string}
   * @memberof InstanceConfigSettingsAdminInput
   */
  distanceUnit?: InstanceConfigSettingsAdminInputDistanceUnitEnum;
  /**
   *
   * @type {string}
   * @memberof InstanceConfigSettingsAdminInput
   */
  currency?: InstanceConfigSettingsAdminInputCurrencyEnum;
  /**
   *
   * @type {number}
   * @memberof InstanceConfigSettingsAdminInput
   */
  maxAssignmentDistance?: number;
  /**
   *
   * @type {number}
   * @memberof InstanceConfigSettingsAdminInput
   */
  maxDriftDistance?: number;
  /**
   *
   * @type {number}
   * @memberof InstanceConfigSettingsAdminInput
   */
  quoteExpirationMinutes?: number;
  /**
   *
   * @type {number}
   * @memberof InstanceConfigSettingsAdminInput
   */
  feePercentageAmount?: number;
  /**
   *
   * @type {number}
   * @memberof InstanceConfigSettingsAdminInput
   */
  quoteRatePerDistanceUnit?: number;
  /**
   * Base fee per delivery, in whole cents (spec 0001). Hand edited.
   * @type {number}
   * @memberof InstanceConfigSettingsAdminInput
   */
  quoteBaseFee?: number;
  /**
   *
   * @type {number}
   * @memberof InstanceConfigSettingsAdminInput
   */
  defaultCourierPayRate?: number;
  /**
   *
   * @type {number}
   * @memberof InstanceConfigSettingsAdminInput
   */
  defaultMaxWorkingHours?: number;
  /**
   *
   * @type {Array<string>}
   * @memberof InstanceConfigSettingsAdminInput
   */
  defaultDietaryRestrictions?: Array<InstanceConfigSettingsAdminInputDefaultDietaryRestrictionsEnum>;
  /**
   *
   * @type {object}
   * @memberof InstanceConfigSettingsAdminInput
   */
  details?: object;
  /**
   *
   * @type {Array<string>}
   * @memberof InstanceConfigSettingsAdminInput
   */
  registeredRegistries?: string[];
  /**
   *
   * @type {{ [key: string]: number }}
   * @memberof InstanceConfigSettingsAdminInput
   */
  reassignmentPayoutPolicies?: { [key: string]: number };
  /**
   *
   * @type {string}
   * @memberof InstanceConfigSettingsAdminInput
   */
  reassignmentPayoutDefaultPolicy?: string;
}

/**
 * @export
 */
export const InstanceConfigSettingsAdminInputCourierMatcherTypeEnum = {
  NearestCourier: "NEAREST_COURIER",
  CourierSeniority: "COURIER_SENIORITY",
  Static: "STATIC",
} as const;
export type InstanceConfigSettingsAdminInputCourierMatcherTypeEnum =
  (typeof InstanceConfigSettingsAdminInputCourierMatcherTypeEnum)[keyof typeof InstanceConfigSettingsAdminInputCourierMatcherTypeEnum];

/**
 * @export
 */
export const InstanceConfigSettingsAdminInputQuoteCalculationTypeEnum = {
  ByDistance: "BY_DISTANCE",
  Surge: "SURGE",
  Custom: "CUSTOM",
} as const;
export type InstanceConfigSettingsAdminInputQuoteCalculationTypeEnum =
  (typeof InstanceConfigSettingsAdminInputQuoteCalculationTypeEnum)[keyof typeof InstanceConfigSettingsAdminInputQuoteCalculationTypeEnum];

/**
 * @export
 */
export const InstanceConfigSettingsAdminInputGeoCalculationTypeEnum = {
  Haversine: "HAVERSINE",
  GoogleMatrixApi: "GOOGLE_MATRIX_API",
  Random: "RANDOM",
  Osrm: "OSRM",
} as const;
export type InstanceConfigSettingsAdminInputGeoCalculationTypeEnum =
  (typeof InstanceConfigSettingsAdminInputGeoCalculationTypeEnum)[keyof typeof InstanceConfigSettingsAdminInputGeoCalculationTypeEnum];

/**
 * @export
 */
export const InstanceConfigSettingsAdminInputDeliveryDurationCalculationTypeEnum =
  {
    Simple: "SIMPLE",
    Osrm: "OSRM",
  } as const;
export type InstanceConfigSettingsAdminInputDeliveryDurationCalculationTypeEnum =
  (typeof InstanceConfigSettingsAdminInputDeliveryDurationCalculationTypeEnum)[keyof typeof InstanceConfigSettingsAdminInputDeliveryDurationCalculationTypeEnum];

/**
 * @export
 */
export const InstanceConfigSettingsAdminInputCourierCompensationCalculationTypeEnum =
  {
    FromQuoteFrom: "FROM_QUOTE_FROM",
  } as const;
export type InstanceConfigSettingsAdminInputCourierCompensationCalculationTypeEnum =
  (typeof InstanceConfigSettingsAdminInputCourierCompensationCalculationTypeEnum)[keyof typeof InstanceConfigSettingsAdminInputCourierCompensationCalculationTypeEnum];

/**
 * @export
 */
export const InstanceConfigSettingsAdminInputDistanceUnitEnum = {
  Kilometers: "KILOMETERS",
  Miles: "MILES",
} as const;
export type InstanceConfigSettingsAdminInputDistanceUnitEnum =
  (typeof InstanceConfigSettingsAdminInputDistanceUnitEnum)[keyof typeof InstanceConfigSettingsAdminInputDistanceUnitEnum];

/**
 * @export
 */
export const InstanceConfigSettingsAdminInputCurrencyEnum = {
  Usd: "USD",
  Eur: "EUR",
} as const;
export type InstanceConfigSettingsAdminInputCurrencyEnum =
  (typeof InstanceConfigSettingsAdminInputCurrencyEnum)[keyof typeof InstanceConfigSettingsAdminInputCurrencyEnum];

/**
 * @export
 */
export const InstanceConfigSettingsAdminInputDefaultDietaryRestrictionsEnum = {
  None: "NONE",
  Vegan: "VEGAN",
  Vegetarian: "VEGETARIAN",
  Halal: "HALAL",
  Kosher: "KOSHER",
  GlutenFree: "GLUTEN_FREE",
  LactoseFree: "LACTOSE_FREE",
  NutFree: "NUT_FREE",
  SeafoodFree: "SEAFOOD_FREE",
  Other: "OTHER",
} as const;
export type InstanceConfigSettingsAdminInputDefaultDietaryRestrictionsEnum =
  (typeof InstanceConfigSettingsAdminInputDefaultDietaryRestrictionsEnum)[keyof typeof InstanceConfigSettingsAdminInputDefaultDietaryRestrictionsEnum];

/**
 * Check if a given object implements the InstanceConfigSettingsAdminInput interface.
 */
export function instanceOfInstanceConfigSettingsAdminInput(
  value: object,
): boolean {
  let isInstance = true;

  return isInstance;
}

export function InstanceConfigSettingsAdminInputFromJSON(
  json: any,
): InstanceConfigSettingsAdminInput {
  return InstanceConfigSettingsAdminInputFromJSONTyped(json, false);
}

export function InstanceConfigSettingsAdminInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): InstanceConfigSettingsAdminInput {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    courierMatcherType: !exists(json, "courierMatcherType")
      ? undefined
      : json["courierMatcherType"],
    quoteCalculationType: !exists(json, "quoteCalculationType")
      ? undefined
      : json["quoteCalculationType"],
    geoCalculationType: !exists(json, "geoCalculationType")
      ? undefined
      : json["geoCalculationType"],
    deliveryDurationCalculationType: !exists(
      json,
      "deliveryDurationCalculationType",
    )
      ? undefined
      : json["deliveryDurationCalculationType"],
    courierCompensationCalculationType: !exists(
      json,
      "courierCompensationCalculationType",
    )
      ? undefined
      : json["courierCompensationCalculationType"],
    distanceUnit: !exists(json, "distanceUnit")
      ? undefined
      : json["distanceUnit"],
    currency: !exists(json, "currency") ? undefined : json["currency"],
    maxAssignmentDistance: !exists(json, "maxAssignmentDistance")
      ? undefined
      : json["maxAssignmentDistance"],
    maxDriftDistance: !exists(json, "maxDriftDistance")
      ? undefined
      : json["maxDriftDistance"],
    quoteExpirationMinutes: !exists(json, "quoteExpirationMinutes")
      ? undefined
      : json["quoteExpirationMinutes"],
    feePercentageAmount: !exists(json, "feePercentageAmount")
      ? undefined
      : json["feePercentageAmount"],
    quoteRatePerDistanceUnit: !exists(json, "quoteRatePerDistanceUnit")
      ? undefined
      : json["quoteRatePerDistanceUnit"],
    defaultCourierPayRate: !exists(json, "defaultCourierPayRate")
      ? undefined
      : json["defaultCourierPayRate"],
    quoteBaseFee: !exists(json, "quoteBaseFee")
      ? undefined
      : json["quoteBaseFee"],
    defaultMaxWorkingHours: !exists(json, "defaultMaxWorkingHours")
      ? undefined
      : json["defaultMaxWorkingHours"],
    defaultDietaryRestrictions: !exists(json, "defaultDietaryRestrictions")
      ? undefined
      : json["defaultDietaryRestrictions"],
    details: !exists(json, "details") ? undefined : json["details"],
    registeredRegistries: !exists(json, "registeredRegistries")
      ? undefined
      : (json["registeredRegistries"] as string[]),
    reassignmentPayoutPolicies: !exists(json, "reassignmentPayoutPolicies")
      ? undefined
      : json["reassignmentPayoutPolicies"],
    reassignmentPayoutDefaultPolicy: !exists(
      json,
      "reassignmentPayoutDefaultPolicy",
    )
      ? undefined
      : json["reassignmentPayoutDefaultPolicy"],
  };
}

export function InstanceConfigSettingsAdminInputToJSON(
  value?: InstanceConfigSettingsAdminInput | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    courierMatcherType: value.courierMatcherType,
    quoteCalculationType: value.quoteCalculationType,
    geoCalculationType: value.geoCalculationType,
    deliveryDurationCalculationType: value.deliveryDurationCalculationType,
    courierCompensationCalculationType:
      value.courierCompensationCalculationType,
    distanceUnit: value.distanceUnit,
    currency: value.currency,
    maxAssignmentDistance: value.maxAssignmentDistance,
    maxDriftDistance: value.maxDriftDistance,
    quoteExpirationMinutes: value.quoteExpirationMinutes,
    feePercentageAmount: value.feePercentageAmount,
    defaultCourierPayRate: value.defaultCourierPayRate,
    defaultMaxWorkingHours: value.defaultMaxWorkingHours,
    defaultDietaryRestrictions: value.defaultDietaryRestrictions,
    details: value.details,
    registeredRegistries: value.registeredRegistries,
    quoteRatePerDistanceUnit: value.quoteRatePerDistanceUnit,
    quoteBaseFee: value.quoteBaseFee,
    reassignmentPayoutPolicies: value.reassignmentPayoutPolicies,
    reassignmentPayoutDefaultPolicy: value.reassignmentPayoutDefaultPolicy,
  };
}
