/* tslint:disable */
/* eslint-disable */
/**
 * OPENCOURIER-API
 * OpenCourier Backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstanceConfigSettingsOptionsDto
 */
export interface InstanceConfigSettingsOptionsDto {
    /**
     * 
     * @type {Array<string>}
     * @memberof InstanceConfigSettingsOptionsDto
     */
    courierMatcherType: Array<InstanceConfigSettingsOptionsDtoCourierMatcherTypeEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof InstanceConfigSettingsOptionsDto
     */
    quoteCalculationType: Array<InstanceConfigSettingsOptionsDtoQuoteCalculationTypeEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof InstanceConfigSettingsOptionsDto
     */
    geoCalculationType: Array<InstanceConfigSettingsOptionsDtoGeoCalculationTypeEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof InstanceConfigSettingsOptionsDto
     */
    deliveryDurationCalculationType: Array<InstanceConfigSettingsOptionsDtoDeliveryDurationCalculationTypeEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof InstanceConfigSettingsOptionsDto
     */
    courierCompensationCalculationType: Array<InstanceConfigSettingsOptionsDtoCourierCompensationCalculationTypeEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof InstanceConfigSettingsOptionsDto
     */
    defaultDietaryRestrictions: Array<InstanceConfigSettingsOptionsDtoDefaultDietaryRestrictionsEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof InstanceConfigSettingsOptionsDto
     */
    distanceUnit: Array<InstanceConfigSettingsOptionsDtoDistanceUnitEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof InstanceConfigSettingsOptionsDto
     */
    currency: Array<InstanceConfigSettingsOptionsDtoCurrencyEnum>;
}


/**
 * @export
 */
export const InstanceConfigSettingsOptionsDtoCourierMatcherTypeEnum = {
    NearestCourier: 'NEAREST_COURIER',
    CourierSeniority: 'COURIER_SENIORITY',
    Static: 'STATIC'
} as const;
export type InstanceConfigSettingsOptionsDtoCourierMatcherTypeEnum = typeof InstanceConfigSettingsOptionsDtoCourierMatcherTypeEnum[keyof typeof InstanceConfigSettingsOptionsDtoCourierMatcherTypeEnum];

/**
 * @export
 */
export const InstanceConfigSettingsOptionsDtoQuoteCalculationTypeEnum = {
    ByDistance: 'BY_DISTANCE',
    Surge: 'SURGE',
    Custom: 'CUSTOM'
} as const;
export type InstanceConfigSettingsOptionsDtoQuoteCalculationTypeEnum = typeof InstanceConfigSettingsOptionsDtoQuoteCalculationTypeEnum[keyof typeof InstanceConfigSettingsOptionsDtoQuoteCalculationTypeEnum];

/**
 * @export
 */
export const InstanceConfigSettingsOptionsDtoGeoCalculationTypeEnum = {
    Haversine: 'HAVERSINE',
    GoogleMatrixApi: 'GOOGLE_MATRIX_API',
    Random: 'RANDOM',
    Osrm: 'OSRM'
} as const;
export type InstanceConfigSettingsOptionsDtoGeoCalculationTypeEnum = typeof InstanceConfigSettingsOptionsDtoGeoCalculationTypeEnum[keyof typeof InstanceConfigSettingsOptionsDtoGeoCalculationTypeEnum];

/**
 * @export
 */
export const InstanceConfigSettingsOptionsDtoDeliveryDurationCalculationTypeEnum = {
    Simple: 'SIMPLE',
    Osrm: 'OSRM'
} as const;
export type InstanceConfigSettingsOptionsDtoDeliveryDurationCalculationTypeEnum = typeof InstanceConfigSettingsOptionsDtoDeliveryDurationCalculationTypeEnum[keyof typeof InstanceConfigSettingsOptionsDtoDeliveryDurationCalculationTypeEnum];

/**
 * @export
 */
export const InstanceConfigSettingsOptionsDtoCourierCompensationCalculationTypeEnum = {
    FromQuoteFrom: 'FROM_QUOTE_FROM'
} as const;
export type InstanceConfigSettingsOptionsDtoCourierCompensationCalculationTypeEnum = typeof InstanceConfigSettingsOptionsDtoCourierCompensationCalculationTypeEnum[keyof typeof InstanceConfigSettingsOptionsDtoCourierCompensationCalculationTypeEnum];

/**
 * @export
 */
export const InstanceConfigSettingsOptionsDtoDefaultDietaryRestrictionsEnum = {
    None: 'NONE',
    Vegan: 'VEGAN',
    Vegetarian: 'VEGETARIAN',
    Halal: 'HALAL',
    Kosher: 'KOSHER',
    GlutenFree: 'GLUTEN_FREE',
    LactoseFree: 'LACTOSE_FREE',
    NutFree: 'NUT_FREE',
    SeafoodFree: 'SEAFOOD_FREE',
    Other: 'OTHER'
} as const;
export type InstanceConfigSettingsOptionsDtoDefaultDietaryRestrictionsEnum = typeof InstanceConfigSettingsOptionsDtoDefaultDietaryRestrictionsEnum[keyof typeof InstanceConfigSettingsOptionsDtoDefaultDietaryRestrictionsEnum];

/**
 * @export
 */
export const InstanceConfigSettingsOptionsDtoDistanceUnitEnum = {
    Kilometers: 'KILOMETERS',
    Miles: 'MILES'
} as const;
export type InstanceConfigSettingsOptionsDtoDistanceUnitEnum = typeof InstanceConfigSettingsOptionsDtoDistanceUnitEnum[keyof typeof InstanceConfigSettingsOptionsDtoDistanceUnitEnum];

/**
 * @export
 */
export const InstanceConfigSettingsOptionsDtoCurrencyEnum = {
    Usd: 'USD',
    Eur: 'EUR'
} as const;
export type InstanceConfigSettingsOptionsDtoCurrencyEnum = typeof InstanceConfigSettingsOptionsDtoCurrencyEnum[keyof typeof InstanceConfigSettingsOptionsDtoCurrencyEnum];


/**
 * Check if a given object implements the InstanceConfigSettingsOptionsDto interface.
 */
export function instanceOfInstanceConfigSettingsOptionsDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "courierMatcherType" in value;
    isInstance = isInstance && "quoteCalculationType" in value;
    isInstance = isInstance && "geoCalculationType" in value;
    isInstance = isInstance && "deliveryDurationCalculationType" in value;
    isInstance = isInstance && "courierCompensationCalculationType" in value;
    isInstance = isInstance && "defaultDietaryRestrictions" in value;
    isInstance = isInstance && "distanceUnit" in value;
    isInstance = isInstance && "currency" in value;

    return isInstance;
}

export function InstanceConfigSettingsOptionsDtoFromJSON(json: any): InstanceConfigSettingsOptionsDto {
    return InstanceConfigSettingsOptionsDtoFromJSONTyped(json, false);
}

export function InstanceConfigSettingsOptionsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstanceConfigSettingsOptionsDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'courierMatcherType': json['courierMatcherType'],
        'quoteCalculationType': json['quoteCalculationType'],
        'geoCalculationType': json['geoCalculationType'],
        'deliveryDurationCalculationType': json['deliveryDurationCalculationType'],
        'courierCompensationCalculationType': json['courierCompensationCalculationType'],
        'defaultDietaryRestrictions': json['defaultDietaryRestrictions'],
        'distanceUnit': json['distanceUnit'],
        'currency': json['currency'],
    };
}

export function InstanceConfigSettingsOptionsDtoToJSON(value?: InstanceConfigSettingsOptionsDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'courierMatcherType': value.courierMatcherType,
        'quoteCalculationType': value.quoteCalculationType,
        'geoCalculationType': value.geoCalculationType,
        'deliveryDurationCalculationType': value.deliveryDurationCalculationType,
        'courierCompensationCalculationType': value.courierCompensationCalculationType,
        'defaultDietaryRestrictions': value.defaultDietaryRestrictions,
        'distanceUnit': value.distanceUnit,
        'currency': value.currency,
    };
}

