/* tslint:disable */
/* eslint-disable */
/**
 * OPENCOURIER-API
 * OpenCourier Backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LocationAdminDto
 */
export interface LocationAdminDto {
    /**
     * 
     * @type {string}
     * @memberof LocationAdminDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof LocationAdminDto
     */
    addressLine1: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocationAdminDto
     */
    addressLine2: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocationAdminDto
     */
    city: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocationAdminDto
     */
    state: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocationAdminDto
     */
    street: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocationAdminDto
     */
    zipCode: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocationAdminDto
     */
    countryCode: LocationAdminDtoCountryCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof LocationAdminDto
     */
    stateCode: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocationAdminDto
     */
    houseNumber: string | null;
    /**
     * 
     * @type {number}
     * @memberof LocationAdminDto
     */
    longitude: number;
    /**
     * 
     * @type {number}
     * @memberof LocationAdminDto
     */
    latitude: number;
    /**
     * 
     * @type {string}
     * @memberof LocationAdminDto
     */
    formattedAddress: string | null;
    /**
     * 
     * @type {Date}
     * @memberof LocationAdminDto
     */
    createdAt: Date;
}


/**
 * @export
 */
export const LocationAdminDtoCountryCodeEnum = {
    Us: 'US',
    Gr: 'GR',
    Ca: 'CA',
    Gb: 'GB',
    Au: 'AU',
    Mx: 'MX'
} as const;
export type LocationAdminDtoCountryCodeEnum = typeof LocationAdminDtoCountryCodeEnum[keyof typeof LocationAdminDtoCountryCodeEnum];


/**
 * Check if a given object implements the LocationAdminDto interface.
 */
export function instanceOfLocationAdminDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "addressLine1" in value;
    isInstance = isInstance && "addressLine2" in value;
    isInstance = isInstance && "city" in value;
    isInstance = isInstance && "state" in value;
    isInstance = isInstance && "street" in value;
    isInstance = isInstance && "zipCode" in value;
    isInstance = isInstance && "countryCode" in value;
    isInstance = isInstance && "stateCode" in value;
    isInstance = isInstance && "houseNumber" in value;
    isInstance = isInstance && "longitude" in value;
    isInstance = isInstance && "latitude" in value;
    isInstance = isInstance && "formattedAddress" in value;
    isInstance = isInstance && "createdAt" in value;

    return isInstance;
}

export function LocationAdminDtoFromJSON(json: any): LocationAdminDto {
    return LocationAdminDtoFromJSONTyped(json, false);
}

export function LocationAdminDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationAdminDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'addressLine1': json['addressLine1'],
        'addressLine2': json['addressLine2'],
        'city': json['city'],
        'state': json['state'],
        'street': json['street'],
        'zipCode': json['zipCode'],
        'countryCode': json['countryCode'],
        'stateCode': json['stateCode'],
        'houseNumber': json['houseNumber'],
        'longitude': json['longitude'],
        'latitude': json['latitude'],
        'formattedAddress': json['formattedAddress'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function LocationAdminDtoToJSON(value?: LocationAdminDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'addressLine1': value.addressLine1,
        'addressLine2': value.addressLine2,
        'city': value.city,
        'state': value.state,
        'street': value.street,
        'zipCode': value.zipCode,
        'countryCode': value.countryCode,
        'stateCode': value.stateCode,
        'houseNumber': value.houseNumber,
        'longitude': value.longitude,
        'latitude': value.latitude,
        'formattedAddress': value.formattedAddress,
        'createdAt': (value.createdAt.toISOString()),
    };
}

