/* tslint:disable */
/* eslint-disable */
/**
 * OPENCOURIER-API
 * OpenCourier Backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PartnerAdminDto } from './PartnerAdminDto';
import {
    PartnerAdminDtoFromJSON,
    PartnerAdminDtoFromJSONTyped,
    PartnerAdminDtoToJSON,
} from './PartnerAdminDto';
import type { PaginationDto } from './PaginationDto';
import {
    PaginationDtoFromJSON,
    PaginationDtoFromJSONTyped,
    PaginationDtoToJSON,
} from './PaginationDto';

/**
 * 
 * @export
 * @interface PartnerPaginatedAdminDto
 */
export interface PartnerPaginatedAdminDto {
    /**
     * 
     * @type {Array<PartnerAdminDto>}
     * @memberof PartnerPaginatedAdminDto
     */
    data: Array<PartnerAdminDto>;
    /**
     * 
     * @type {PaginationDto}
     * @memberof PartnerPaginatedAdminDto
     */
    pagination?: PaginationDto;
}

/**
 * Check if a given object implements the PartnerPaginatedAdminDto interface.
 */
export function instanceOfPartnerPaginatedAdminDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function PartnerPaginatedAdminDtoFromJSON(json: any): PartnerPaginatedAdminDto {
    return PartnerPaginatedAdminDtoFromJSONTyped(json, false);
}

export function PartnerPaginatedAdminDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartnerPaginatedAdminDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'data': ((json['data'] as Array<any>).map(PartnerAdminDtoFromJSON)),
        'pagination': !exists(json, 'pagination') ? undefined : PaginationDtoFromJSON(json['pagination']),
    };
}

export function PartnerPaginatedAdminDtoToJSON(value?: PartnerPaginatedAdminDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'data': ((value.data as Array<any>).map(PartnerAdminDtoToJSON)),
        'pagination': PaginationDtoToJSON(value.pagination),
    };
}
