/* tslint:disable */
/* eslint-disable */
/**
 * OPENCOURIER-API
 * OpenCourier Backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';

/**
 * 
 * @export
 * @interface PartnerRotatePasswordAdminInput
 */
export interface PartnerRotatePasswordAdminInput {
    /**
     * 
     * @type {string}
     * @memberof PartnerRotatePasswordAdminInput
     */
    password: string;
}

/**
 * Check if a given object implements the PartnerRotatePasswordAdminInput interface.
 */
export function instanceOfPartnerRotatePasswordAdminInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function PartnerRotatePasswordAdminInputFromJSON(json: any): PartnerRotatePasswordAdminInput {
    return PartnerRotatePasswordAdminInputFromJSONTyped(json, false);
}

export function PartnerRotatePasswordAdminInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartnerRotatePasswordAdminInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'password': json['password'],
    };
}

export function PartnerRotatePasswordAdminInputToJSON(value?: PartnerRotatePasswordAdminInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'password': value.password,
    };
}
