/* tslint:disable */
/* eslint-disable */
/**
 * OPENCOURIER-API
 * OpenCourier Backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LocationAdminDto } from './LocationAdminDto';
import {
    LocationAdminDtoFromJSON,
    LocationAdminDtoFromJSONTyped,
    LocationAdminDtoToJSON,
} from './LocationAdminDto';

/**
 * 
 * @export
 * @interface PartnerAdminDto
 */
export interface PartnerAdminDto {
    /**
     * 
     * @type {string}
     * @memberof PartnerAdminDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerAdminDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerAdminDto
     */
    phoneNumber: string | null;
    /**
     * 
     * @type {string}
     * @memberof PartnerAdminDto
     */
    logo: string | null;
    /**
     * 
     * @type {string}
     * @memberof PartnerAdminDto
     */
    webhookUrl: string | null;
    /**
     * 
     * @type {string}
     * @memberof PartnerAdminDto
     */
    userId: string | null;
    /**
     * 
     * @type {string}
     * @memberof PartnerAdminDto
     */
    email: string | null;
    /**
     * 
     * @type {LocationAdminDto}
     * @memberof PartnerAdminDto
     */
    pickupAddress: LocationAdminDto | null;
    /**
     * 
     * @type {Date}
     * @memberof PartnerAdminDto
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof PartnerAdminDto
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the PartnerAdminDto interface.
 */
export function instanceOfPartnerAdminDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function PartnerAdminDtoFromJSON(json: any): PartnerAdminDto {
    return PartnerAdminDtoFromJSONTyped(json, false);
}

export function PartnerAdminDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartnerAdminDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'id': json['id'],
        'name': json['name'],
        'phoneNumber': !exists(json, 'phoneNumber') ? null : json['phoneNumber'],
        'logo': !exists(json, 'logo') ? null : json['logo'],
        'webhookUrl': !exists(json, 'webhookUrl') ? null : json['webhookUrl'],
        'userId': !exists(json, 'userId') ? null : json['userId'],
        'email': !exists(json, 'email') ? null : json['email'],
        'pickupAddress': !exists(json, 'pickupAddress') || json['pickupAddress'] === null ? null : LocationAdminDtoFromJSON(json['pickupAddress']),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function PartnerAdminDtoToJSON(value?: PartnerAdminDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'id': value.id,
        'name': value.name,
        'phoneNumber': value.phoneNumber,
        'logo': value.logo,
        'webhookUrl': value.webhookUrl,
        'userId': value.userId,
        'email': value.email,
        'pickupAddress': LocationAdminDtoToJSON(value.pickupAddress),
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': (value.updatedAt.toISOString()),
    };
}
