/* tslint:disable */
/* eslint-disable */
/**
 * OPENCOURIER-API
 * OpenCourier Backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    PartnerAdminDto,
    PartnerCreateAdminInput,
    PartnerPaginatedAdminDto,
    PartnerRotatePasswordAdminInput,
    PartnerUpdateAdminInput,
} from '../models/index';
import {
    PartnerAdminDtoFromJSON,
    PartnerAdminDtoToJSON,
    PartnerCreateAdminInputToJSON,
    PartnerPaginatedAdminDtoFromJSON,
    PartnerRotatePasswordAdminInputToJSON,
    PartnerUpdateAdminInputToJSON,
} from '../models/index';

export interface PartnerApiGetPartnersRequest {
    page?: number;
    perPage?: number;
}

export interface PartnerApiGetPartnerRequest {
    id: string;
}

export interface PartnerApiCreatePartnerRequest {
    partnerCreateAdminInput: PartnerCreateAdminInput;
}

export interface PartnerApiUpdatePartnerRequest {
    id: string;
    partnerUpdateAdminInput: PartnerUpdateAdminInput;
}

export interface PartnerApiRotatePartnerPasswordRequest {
    id: string;
    partnerRotatePasswordAdminInput: PartnerRotatePasswordAdminInput;
}

/**
 * 
 */
export class PartnerApi extends runtime.BaseAPI {

    /**
     * List partners (restaurants)
     */
    async getPartnersRaw(requestParameters: PartnerApiGetPartnersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PartnerPaginatedAdminDto>> {
        const queryParameters: any = {};

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.perPage !== undefined) {
            queryParameters['perPage'] = requestParameters.perPage;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/admin/v1/partner`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PartnerPaginatedAdminDtoFromJSON(jsonValue));
    }

    /**
     * List partners (restaurants)
     */
    async getPartners(requestParameters: PartnerApiGetPartnersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PartnerPaginatedAdminDto> {
        const response = await this.getPartnersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get partner by id
     */
    async getPartnerRaw(requestParameters: PartnerApiGetPartnerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PartnerAdminDto>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id', 'Required parameter requestParameters.id was null or undefined when calling getPartner.');
        }

        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/admin/v1/partner/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PartnerAdminDtoFromJSON(jsonValue));
    }

    /**
     * Get partner by id
     */
    async getPartner(requestParameters: PartnerApiGetPartnerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PartnerAdminDto> {
        const response = await this.getPartnerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create partner
     */
    async createPartnerRaw(requestParameters: PartnerApiCreatePartnerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PartnerAdminDto>> {
        if (requestParameters.partnerCreateAdminInput === null || requestParameters.partnerCreateAdminInput === undefined) {
            throw new runtime.RequiredError('partnerCreateAdminInput', 'Required parameter requestParameters.partnerCreateAdminInput was null or undefined when calling createPartner.');
        }

        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};
        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/admin/v1/partner`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PartnerCreateAdminInputToJSON(requestParameters.partnerCreateAdminInput),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PartnerAdminDtoFromJSON(jsonValue));
    }

    /**
     * Create partner
     */
    async createPartner(requestParameters: PartnerApiCreatePartnerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PartnerAdminDto> {
        const response = await this.createPartnerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update partner
     */
    async updatePartnerRaw(requestParameters: PartnerApiUpdatePartnerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PartnerAdminDto>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id', 'Required parameter requestParameters.id was null or undefined when calling updatePartner.');
        }
        if (requestParameters.partnerUpdateAdminInput === null || requestParameters.partnerUpdateAdminInput === undefined) {
            throw new runtime.RequiredError('partnerUpdateAdminInput', 'Required parameter requestParameters.partnerUpdateAdminInput was null or undefined when calling updatePartner.');
        }

        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};
        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/admin/v1/partner/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PartnerUpdateAdminInputToJSON(requestParameters.partnerUpdateAdminInput),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PartnerAdminDtoFromJSON(jsonValue));
    }

    /**
     * Update partner
     */
    async updatePartner(requestParameters: PartnerApiUpdatePartnerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PartnerAdminDto> {
        const response = await this.updatePartnerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Rotate partner password
     */
    async rotatePartnerPasswordRaw(requestParameters: PartnerApiRotatePartnerPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id', 'Required parameter requestParameters.id was null or undefined when calling rotatePartnerPassword.');
        }
        if (requestParameters.partnerRotatePasswordAdminInput === null || requestParameters.partnerRotatePasswordAdminInput === undefined) {
            throw new runtime.RequiredError('partnerRotatePasswordAdminInput', 'Required parameter requestParameters.partnerRotatePasswordAdminInput was null or undefined when calling rotatePartnerPassword.');
        }

        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};
        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/admin/v1/partner/{id}/rotate-password`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PartnerRotatePasswordAdminInputToJSON(requestParameters.partnerRotatePasswordAdminInput),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Rotate partner password
     */
    async rotatePartnerPassword(requestParameters: PartnerApiRotatePartnerPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.rotatePartnerPasswordRaw(requestParameters, initOverrides);
    }
}
